import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers"; 
import Navigation from "./components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vacunas",
  description: "Generated by create next app",
};

// className = { inter.className }
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background w-full">
        <Providers>
          <header>
            <nav className="max-w-5xl m-auto flex justify-between w-full">
              <Navigation />
            </nav>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
